version: '3'
services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./styles.css:/usr/share/nginx/html/styles.css
      - ./logo.png:/usr/share/nginx/html/logo.png